РФ -> Законы

Законы -> Конституция - основной закон

Конституция - основной закон -> Фереральные конституционные законы (ФКЗ)

Фереральные конституционные законы (ФКЗ) -> Конституционные законы

СРФ -> Уставы

СРФ -> Законы

РФ -> Подзаконные НПА

Подзаконные НПА -> Указы Президента
Подзаконные НПА -> Распоряжения Президента

Подзаконные НПА -> Указы Правительства
Подзаконные НПА -> Распоряжения Правительства
Подзаконные НПА -> Акты министерств и ведомств

СРФ -> Подзаконные НПА -> Указы главы СРФ
СРФ -> Подзаконные НПА -> Распоряжения главы СРФ

ОМСУ -> Постановления городской думы
ОМСУ -> Постановления главы города
