Законодательная инициатива -> Государственная Дума
Государственная Дума -> Ответственный комитет
Ответственный комитет -> 1 чтение
1 чтение -> 2 чтение
2 чтение -> 3 чтение
3 чтение -> Совет Федерации
Совет Федерации -> да
Совет Федерации -> нет
да -> Президент
Президент -> Подпись
Президент -> Отклонение
Подпись -> Публикация
Публикация -> Вступление в силу
