#+TITLE: Практическая работа №3
#+AUTHOR: Кормышев Егор ИСиП-401
#+DATE: 23.11.2024
#+LANGUAGE: ru
#+LaTeX_HEADER: \usepackage[russian]{babel}

* Определение
1) Принципы трудового права – это закрепленные в правовых актах общеобязательные положения, идеи начала, которые пронизывают всё трудовое право, выражают тенденции развития и потребности общества и характеризуют трудовое право в целом.
2) Трудовой договор — это соглашение между работодателем и работником, по которому работодатель обеспечивает работника работой и платит за нее зарплату. Взамен работник обязуется добросовестно трудиться и соблюдать правила трудового распорядка, работать лично и не перекладывать свои обязанности на других людей.
3) паспорт или иной документ, удостоверяющий личность; трудовую книжку и (или) сведения о трудовой деятельности (статья 66.1 настоящего Кодекса), за исключением случаев, если трудовой договор заключается впервые; документ, подтверждающий регистрацию в системе индивидуального (персонифицированного) учета, в том числе в форме электронного документа; документы воинского учета - для военнообязанных и лиц, подлежащих призыву на военную службу; документ об образовании и (или) о квалификации или наличии специальных знаний - при поступлении на работу, требующую специальных знаний или специальной подготовки; и другие
4) Лица, для которых не устанавливается испытательный срок:
   
- беременных женщин и женщин, имеющих детей в возрасте до 1,5 лет;
- лиц, которые получили среднее профессиональное образование или высшее образование по имеющим государственную аккредитацию образовательным программам и впервые поступают на работу по полученной специальности в течение 1 года со дня получения образования;
- лиц, приглашенных на работу в порядке перевода от другого работодателя;
- лиц, заключающих трудовой договор на срок до 2 месяцев;
- лиц, не достигших возраста 18 лет;
- лиц, успешно завершивших ученичество, при заключении трудового договора с работодателем, по договору с которым они проходили обучение;
- лиц, избранных по конкурсу на замещение соответствующей должности;
- лиц, избранных на выборную должность на оплачиваемую работу.

* Задачи

* №9

ст 97, 99 ТК РФ

Привлечение к сверхурочной работе возможно только с согласия работника

* №10

ст 80 ТК РФ

До истечения срока предупреждения об увольнении работник имеет право в любое время отозвать свое заявление

* №11

ст 81 ТК РФ

Не допускается увольнение работника в период его временной нетрудоспособности и пребывании в отпуске

* №12

ст 92 ТК РФ

<18 лет - не более 35 часов в неделю

* №13

ст 93 ТК РФ

работа на условиях неполного рабочего времени не влечет для работников каких-либо ограничений продолжительности ежегодного основного оплачиваемого отпуска и других трудовых прав 
